### ISSUE TITLE
Invalid file:/data/data/com.s3samples/files

### ISSUE THREAD

**Issue by shaikhussian** [mybigday/react-native-s3#11]
hai, when i try to run your example in react-native-s3, i got an error as shown in the below image,could you please tell me that how to overcome it,

-npm install

- to run in android: react-native run-android
After that in emulator when click on  New Upload i got an error like below

![screen shot 2016-03-22 at 12 38 35 pm](https://cloud.githubusercontent.com/assets/11956308/13944411/2aae64d8-f02b-11e5-9463-ff015640db4b.png)

please tell me that how to resolve it

**Comment by jhen0409** [comment]
Because the [example](https://github.com/mybigday/react-native-s3/blob/master/example/app.js#L13-L18) is not write the filename, currently you must add it yourself.

I'll providing a example file, and a guide of setting. :)

**Comment by shaikhussian** [comment]
@jhen0409 Thank you for your response, I am waiting for the example file please provide as soon as possible

**Comment by shaikhussian** [comment]
@jhen0409 thanks for your response, can you please provide the working example it would helpful for me

**Comment by jhen0409** [comment]
Sorry for delay, just added example file download in https://github.com/mybigday/react-native-s3/commit/8aa52d6e4537b86c55346a2706b149c6d9221f91.
