### ISSUE TITLE
[iOS] RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSURL)

### ISSUE THREAD

**Issue by t-unit** [mybigday/react-native-s3#13]
If an upload fails for some reason the `userInfo` property of the error might contain types that are not valid JSON types. [This](https://github.com/mybigday/react-native-s3/blob/master/ios/RNS3/RNS3TransferUtility.m#L128) code causing the problem:
```objc
    errorObj = @{
      […]
      @"userInfo": [error userInfo]
    };
```

Simply passing `userInfo` back to react native seem to be not a good idea. A simple fix could be to remove the `userInfo` here. Happy to supply a PR if you want.

**Comment by jhen0409** [comment]
You're right, maybe we should use `error.localizedDescription` instead? PR welcome, thanks. :)

**Comment by athibaud** [comment]
@jhen0409 hi there, would you mind publishing a package containing this fix to npm please :)
