### ISSUE TITLE
Feature request: user provided metadata "x-amz-meta-"

### ISSUE THREAD

**Issue by alfonsodev** [mybigday/react-native-s3#16]
Hi, thanks for this great module.
It would be cool to have the possibility to add custom meta information, 
AWS provides the prefix  'x-amz-meta-'  for this propose   https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata 

It seems that the [aws-sdk-ios has the possibility to add metada](https://github.com/aws/aws-sdk-ios/issues/277) by calling the AWSS3TransferUtilityExpression  method [setValue:forRequestParam]](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtilityExpression.html#//api/name/setValue:forRequestParameter:)  
So in Javascript the call would be like  

```js 
  const task = await transferUtility.upload({
          bucket: 'ghinwa-songs',
          key: 'uploads/foo.mp3',
          file: 'tmp/123abc.mp3',
          meta: {
            contentType: 'audio/mpeg',
            'x-amz-meta-my-custom-data': 'here'
          }
        })
```
I don't have much experience with Objective-c but I see that in [RNS3TransferUtility.m line 224](https://github.com/mybigday/react-native-s3/blob/a1b79c45afb385d6fdb80e7f15a50074922bb39d/ios/RNS3/RNS3TransferUtility.m#L224)
There should be a way to get every key of the meta object that starts by 'x-amz-meta-' and for call the setValue method of expression, right ? 
Are you interested in adding this change ? are my assumptions correct ?  
Thanks.

**Comment by jhen0409** [comment]
Added by https://github.com/mybigday/react-native-s3/commit/526cc87a95c366d60681ce9a4c38b90a13dc79ad, released in v0.0.13.
