### ISSUE TITLE
it is not working on iOS9

### ISSUE THREAD

**Issue by binzailani3136** [mybigday/react-native-s3#19]
Could you fix this issue please?

**Comment by jhen0409** [comment]
Could you please provide more information for this? I also used this package on iOS 9.

Maybe #9 can be help you?

**Comment by binzailani3136** [comment]
Thanks for your reply.
In readme file, it is mentioned as below.
<NOTE Only supported iOS ^8.0.>

Is this library is available to use in iOS9.0?
I would like to know if I can use this library to upload image or video files to amazon s3 cloud front bucket.
I want to use this on both Android6.0 and iOS9.0.
Can I use this library for these platforms?

**Comment by darrenfurr** [comment]
I just configured this library with iOS 9.3 & it works fine. Because of the issue #9 you cannot reload the simulator, but otherwise it works great. Thanks guys!
