### ISSUE TITLE
constant state of WAITING on IOS

### ISSUE THREAD

**Issue by proProbe** [mybigday/react-native-s3#28]
Hello!

Thanks for the great library. Im currently having some problems on IOS where the state never switches from `waiting` to `in_progress` during an upload.

My use case is the following:
A user may update his/hers profile picture. This is sent to aws3 and stored there. This image is taken by an imagepicker and could be either from  the camera directly or from the camera roll.

The problem Im having is that updating it `once` works perfectly well! It's when you try to update it `twice and more` that the state never shifts from `waiting` to `in_progess`.

One thing I noticed is that it works perfectly well on Android. Its only IOS that it doesnt work for. Any ideas?

**Comment by jhen0409** [comment]
It looks appears in the recent iOS SDK versions, I'm pretty sure it's related to native code, I'll look at it in next few days.

**Comment by proProbe** [comment]
@jhen0409 great to hear! Im looking forward to get this to work. Ive been using react-native-aws3 before but as it doesnt have the background upload

**Comment by ox-michaelradionov** [comment]
I have the same problem, task is always stuck on `waiting` state on iOS. Even though the content is uploaded at some point, there is no way to know when upload is completed or failed, event listeners attached via `transferUtility.subscribe` never get fired.
I am using AWS SDK for iOS which are installed along with your library, I am able to reproduce it on all iOS devices I have.
It works like a charm on Android, thanks for your work!

**Comment by indesignlatam** [comment]
I was having this issue and I realized that the NSURLSession was created multiple times, so I setup now on my main component constructor and this just runs once.

transferUtility.setupWithNative(); // Call this on your main component where it will only be called once.

This solved my issue, maybe it will solve yours.

**Comment by ox-michaelradionov** [comment]
@indesignlatam , Thank you so much, it solved the issue. I was calling `setupWith*` function before every call I was making to `transferUtility`, just it case it's not authorized. I even had errors in XCode console:

> A background URLSession with identifier com.amazonaws.AWSS3TransferUtility.Identifier.RNS3TransferUtility already exists!

by I did not pay attention to it and spent a lot of time trying to debug react-native-s3 native code and aws sdk. 
I've moved the setup code to the main component as you said and progress/complete handlers started working. Thanks for your help once again.

**Comment by jhen0409** [comment]
@ox-michaelradionov your problem may related to #9 (we are still [trying to solve](https://github.com/mybigday/react-native-s3/pull/27)) not here.

**Comment by proProbe** [comment]
@indesignlatam so the solution is to have it only initiate once (through for example the main component)? Gonna try this later. If it works, Ill consider it as a solution to this issue and will close it

**Comment by indesignlatam** [comment]
@proProbe Is a workaround and not a solution, if you reload the app it will stop working again. But the tracking of this issue must be done in #9 if this works for you.

**Comment by proProbe** [comment]
@indesignlatam I see! Ill keep track of #9 and hope for a solution in there

**Comment by jhen0409** [comment]
Fixed in #33. (v0.0.23)
