### ISSUE TITLE
NotAuthorizedException

### ISSUE THREAD

**Issue by damathryx** [mybigday/react-native-s3#30]
I'm getting

> UploadTask: Failed to upload: 11 due to Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException;

error in logcat.
setupWithCognito return true. What am I missing?
I'm new to AWS so I am not sure where to look.

**Comment by Blapi** [comment]
Hey @damathryx , I see you closed this issue with no solution. How did you handle this please?

**Comment by damathryx** [comment]
@Blapi if my memory serves me right I was missing this on AndroidManifest

`<service
  android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
  android:enabled="true" />`
