### ISSUE TITLE
Progress Not Updating!

### ISSUE THREAD

**Issue by DHidee66** [mybigday/react-native-s3#4]
Hi,

So during the upload I subscribe to the event and I get this results:
![screen shot 2016-03-13 at 3 12 48 pm](https://cloud.githubusercontent.com/assets/6751025/13729170/44bb6478-e92f-11e5-8f46-9f2e45a8ff42.png)
Should the `bytes` be different than 0 during `in_progress`?

Thank You!

**Comment by jhen0409** [comment]
Thanks for report!
It looks [new TransferObserver instance](https://github.com/mybigday/react-native-s3/blob/master/android/src/main/java/com/mybigday/rn/RNS3TransferUtility.java#L96) cannot get bytesTransfered, this is a strange problem. Maybe it's official SDK problem, or I overlooked something. I'll tracking this issue. :)

**Comment by jhen0409** [comment]
It fixed by https://github.com/mybigday/react-native-s3/commit/84a63481c7de911f211784643b60820330f20cb8, it temporarily use `AsyncStorage` save `bytesCurrent`, like iOS version.
