### ISSUE TITLE
AWSS3TransferUtilityErrorDomain error 2

### ISSUE THREAD

**Issue by damathryx** [mybigday/react-native-s3#41]
version - v0.0.24
react-native - 0.38

using `transferUtility.setupWithBasic(accessKey, secretKey, sessionKey)`
getting this error (only in iOS, android is working fine) on `transferUtility.subscribe(id, (err, task)`

> The operation couldn’t be completed. (com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.

after it fails when upload reaches 100%. 
![screen shot 2017-02-24 at 10 40 06 pm](https://cloud.githubusercontent.com/assets/14576761/23307484/b09ffb3e-fae2-11e6-86dd-6c2c56b715be.png)

What am i missing?

**Comment by jhen0409** [comment]
Is `sessionKey` you set to object, not [`sessionToken`](https://github.com/mybigday/react-native-s3/blob/master/API.md#transferutilitysetupwithbasicoptions)?

**Comment by damathryx** [comment]
Sorry for the late update. I already have fixed the issue. It was due to wrong region supplied. (sigh) but im wondering why its working on android though.
Closing this issue.
