### ISSUE TITLE
Build error ios

### ISSUE THREAD

**Issue by TheMarsGuy** [mybigday/react-native-s3#47]
Getting this error.

ld: framework not found AWSCore for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vTrip** [comment]
I have this issue when archiving the build. Framework is missing arm 64 in file.

**Comment by wkrause13** [comment]
@TheMarsGuy, Did you happen to figure out how to address this?

**Comment by TheMarsGuy** [comment]
I might have figured it out, not sure it was a while back. I guess I dumped this library for the official aws package for react-native, as I wanted to download files too.

**Comment by wkrause13** [comment]
Thanks, I ended up manually linking the required frameworks and then using this script in order to enable uploads to the app store. Seems to be working as of right now. 

https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive
