### ISSUE TITLE
Uploading a file with public-read

### ISSUE THREAD

**Issue by Blapi** [mybigday/react-native-s3#48]
Hi, I'm trying to upload some files on my s3 with this package. It's working well but I'm having an issue because I've got an "Access denied" when I want to access to the file. I'd like it to be public-read and I'm doing this

```
      const uploadOptions = {
        'bucket': config.aws.bucket,
        'key': `${config.aws.identityPoolId}/${uuid.v1().slice(0, 7)}.jpeg`,
        'file': file,
        'meta': {
          'Content-Type': 'image/jpeg',
          'x-amz-acl': 'public-read'
        }
      }

      const task = await transferUtility.upload(uploadOptions)
```

when I'm uploading a file but I still have the 'Access denied', even if with the public-read acl.

Any help on this please?

**Comment by Blapi** [comment]
@jhen0409, any help on this please?

**Comment by aronse** [comment]
I'm facing the same problem here @jhen0409 , any way to pass the ACL?

**Comment by Blapi** [comment]
Ended up adding the missing informations in your library.

**Comment by vTrip** [comment]
@Blapi what was the solution to this issue ?

**Comment by Blapi** [comment]
Hey @vTrip, I'm now using https://github.com/aronse/react-native-s3 which is a fork of this repo.

Now, you can manage case "**private**", case "**public-read**", case "**public-read-write**", case "**authenticated-read**", case "**bucket-owner-read**", case "**bucket-owner-full-control**", and the case "**log-delivery-write**"

You use this like this : 

        const uploadOptions = {
          'bucket': config.aws.bucket,
          'key': anyKey,
          'file': file,
          'acl': 'public-read', // add the case you want
          'meta': {
            'Content-Type': type.contentType
          }

Hope this helps !

**Comment by Blapi** [comment]
Working on Android, don't know if it's working on iOS

**Comment by jhen0409** [comment]
I think set `meta: { 'x-amz-acl': 'public-read' }` for options should just work on iOS ([the code](https://github.com/mybigday/react-native-s3/blob/master/ios/RNS3/RNS3TransferUtility.m#L261-L266)), but Android probably not.

I'll back working on this but not very soon, feel free to submit a PR for this!

**Comment by aronse** [comment]
@jhen0409 I just submitted a PR (https://github.com/mybigday/react-native-s3/pull/50). Let me know if you need me to change anything. This was just a quick and dirty fix so it may not be the cleanest way to do it.
