### ISSUE TITLE
Are you planning on adding iOS support for deleteRecord?

### ISSUE THREAD

**Issue by ericvillemure** [mybigday/react-native-s3#51]
Hi guys today I am working on the iOS implementation of a new app we are building using react-native.  I just realised that transferUtility.deleteRecord throws a "Not Implemented" error.  After double checking the documentation I can see that there is an (Android) label next to deleteRecord.  I was wondering if you are planning on implementing it in iOS as well and when.

Thanks

**Comment by jhen0409** [comment]
The iOS native SDK haven't `deleteRecord` way. The completed task will not be persisted after app restart for iOS, but Android will.
