### ISSUE TITLE
Method does not override or implement a method from a supertype [Android]

### ISSUE THREAD

**Issue by rpastorelle** [mybigday/react-native-s3#52]
Using RN 0.47.0

Error in `RNS3Package.java`:

```
RNS3Package.java:21: error: method does not override or implement a method from a supertype
  @Override
  ^
```

## Solution:

Comment out `@Override` here: https://github.com/mybigday/react-native-s3/blob/master/android/src/main/java/com/mybigday/rns3/RNS3Package.java#L21

**Comment by jhen0409** [comment]
Fixed in #53.
