### ISSUE TITLE
Build failing during linking on "RNS3TransferUtility.h"

### ISSUE THREAD

**Issue by benjreinhart** [mybigday/react-native-s3#6]
While setting up react-native-s3, I followed all the steps under Setup -> iOS. When I went to build, the linker failed on the following line in `AppDelegate.m`:

```c
#import "RNS3TransferUtility.h"
```

I added `node_modules/react-native-s3/ios/RNS3/RNS3TransferUtility.h` to `Build Phases` -> `Compile Sources`and then my project compiled. However, given all the steps in the setup instructions in the readme, I'm not sure this step is / should be required? Is there something else I missed?

**Comment by jhen0409** [comment]
Oh, it's less a step. Add `$(SRCROOT)/../node_modules/react-native-s3/ios` to `Header Search Paths`, and mark it as `recursive`. I'll fix readme. :)

**Comment by benjreinhart** [comment]
Thanks, seems like that works!
