### ISSUE TITLE
Cannot cancel a task on iOS

### ISSUE THREAD

**Issue by rickcha** [mybigday/react-native-s3#62]
`var tasks = await transferUtility.getTasks("upload", false);`
`tasks.forEach(()=>{
    transferUtility.cancel(task.id);
});`

And here is an error log:

2018-03-02 19:58:26.720984-0800 vqa[2254:993877] -[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b2bca650
2018-03-02 19:58:26.724078-0800 vqa[2254:993877] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b2bca650'
*** First throw call stack:
(0x181af2364 0x180d38528 0x181aff828 0x181af7d10 0x1819dcecc 0x10422f57c 0x104230174 0x1054587e8 0x10545f65c 0x10545fbac 0x1054583e4 0x105457f24 0x10545a6a8 0x1054589f4 0x1054587e8 0x10545f65c 0x10545fbac 0x1054583e4 0x105457f24 0x10545a6a8 0x104ffa33c 0x1822319d8 0x182133598 0x1824c9ba0 0x182409894 0x1823f94c4 0x10595128c 0x10595d9e4 0x10595128c 0x10595d9e4 0x10595d8a4 0x1824cb878 0x10595128c 0x10595e678 0x10595cf08 0x1059629d0 0x1059626f4 0x18171706c 0x181716b6c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ghost** [comment]
@rickcha it is working fine for me with version 0.0.29. You need to make sure that the task has not already been completed or it will crash. We implement that logic at a higher level and keep track of all tasks and their state. Also, note that on iOS when you cancel a task the plugin returns a 'failed' while on Android it returns a 'canceled'

**Comment by rickcha** [comment]
I am going to close this item. The crash was at some other place than the cancel functionality.
