### ISSUE TITLE
Attempting to call `getTask` throws exception

### ISSUE THREAD

**Issue by benjreinhart** [mybigday/react-native-s3#8]
Every time I try to call `getTask` with the task `id` returned from `upload`, I see the following error:

![screen shot 2016-03-16 at 5 02 14 pm](https://cloud.githubusercontent.com/assets/606233/13859089/a89698d2-ec4f-11e5-82e8-ccd2b54b71db.png)

However, the uploading does work. I just can't seem to use `getTask`. I did notice that if I put in a long timeout (1500ms) between when the promise from `upload` resolves and calling `getTask`, it does not throw that error. But I get `null` back.

`getTasks` seems to work, but it always returns an empty array.

**Comment by jhen0409** [comment]
It fixed by https://github.com/mybigday/react-native-s3/commit/5a045693a245726712776471bf7739d2f389256e, I'll publish v0.0.4. :)

Also, the `getTasks` is need `type` argument (see [this](https://github.com/mybigday/react-native-s3#transferutilitygettaskstype-idaskey)), it should be work.

**Comment by benjreinhart** [comment]
Cool, thanks!

Yeah I was passing `upload` to `getTasks`
