### ISSUE TITLE
[iOS] Support JS reload for TransferUtility

### ISSUE THREAD

**Issue by jhen0409** [mybigday/react-native-s3#9]
When we reload js in iOS, the `transferUtility` upload/download will not work.

**Comment by cyyuen** [comment]
Hey @jhen0409 . Any plan to fix this issue?

**Comment by magbicaleman** [comment]
@jhen0409, also like to follow up on this. The issue I'm having is not uploading issue (uploading) works fine, but the `.subscribe`, is not running after second upload. So I can not update the UI to verify that an upload has been completed.

**Comment by proProbe** [comment]
Would love to get this to work again. Any plans to get this fixed soon?

**Comment by proProbe** [comment]
anyone?

**Comment by jhen0409** [comment]
The problem is related to #27, I'll fix it on next Monday, a workaround [here](https://github.com/mybigday/react-native-s3/pull/27#issuecomment-265954920), we may add `rememberLastInstance` option (default: true) for setup. Sorry for long delay.

The goal is #10 but will not be right now.

**Comment by proProbe** [comment]
great! Im eagerly waiting for the fix!
